name: DVC

on:
  push:
    branches:
      - main  

jobs:
  dvc-setup-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install DVC with Google Drive support
        run: pip install dvc[gdrive]
        
      - name: Install Google Cloud SDK
        run: |
          curl https://sdk.cloud.google.com | bash
          echo "$HOME/google-cloud-sdk/bin" >> $GITHUB_PATH

      - name: Configure Google Drive credentials
        env:
          GDRIVE_SERVICE_ACCOUNT_JSON: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
        run: |
          echo "$GDRIVE_SERVICE_ACCOUNT_JSON" > service-account.json
          dvc remote modify remotekate gdrive_service_account_json_file_path service-account.json
          dvc remote modify remotekate gdrive_use_service_account true

      - name: DVC Pull Data
        run: dvc pull  # Скачиваем все зависимости

      - name: Run DVC Pipeline
        run: |
          dvc repro  # Запускаем пайплайн

      - name: DVC Push Data
        run: |
          dvc push  # Отправляем результаты

      - name: Git add and commit DVC files
        run: |
          git config user.email "ekater_1997@mail.ru"  
          git config user.name "KateProxa" 
          git add .dvc dvc.lock
    
          if [[ $(git status --porcelain | grep -c "dvc.lock\|.dvc") -ne 0 ]]; then
            git commit -m "Update DVC outputs"
          else
            echo "No changes to commit"
          fi

      - name: Git push DVC Config
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTIONS_PAT }}
          branch: ${{ github.ref }}